name: Auto Update Build Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'public/version.js'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Build Number & Update File
        run: |
          VERSION_NUM=$(git rev-list --count HEAD)
          echo "export const APP_VERSION = 'Build #$VERSION_NUM';" > public/version.js
          echo "New Version Generated: Build #$VERSION_NUM"

      - name: Commit and Push Version Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if ! git diff --exit-code public/version.js; then
            git add public/version.js
            git commit -m "chore: automatic version bump [skip ci]"
            git push
          fi
